// * generated by claude sonnet 4.5
package goSqlite

import (
	"database/sql"
	"os"
	"path/filepath"
	"testing"
)

func setupTestDB(t *testing.T) (*Database, *sql.DB, string) {
	t.Helper()

	dbPath := filepath.Join(t.TempDir(), "test.db")
	database, db, err := New(Config{
		Key:      "test_" + t.Name(),
		Path:     dbPath,
		Lifetime: 30,
	})
	if err != nil {
		t.Fatalf("failed to create database: %v", err)
	}

	return database, db, dbPath
}

func TestNew(t *testing.T) {
	t.Run("create new database", func(t *testing.T) {
		dbPath := filepath.Join(t.TempDir(), "test.db")
		database, db, err := New(Config{
			Key:      "test_new",
			Path:     dbPath,
			Lifetime: 30,
		})
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if database == nil {
			t.Fatal("expected database instance, got nil")
		}
		if db == nil {
			t.Fatal("expected db instance, got nil")
		}
		defer database.Close()

		if _, err := os.Stat(dbPath); os.IsNotExist(err) {
			t.Fatalf("database file not created at %s", dbPath)
		}
	})

	t.Run("reuse existing database connection", func(t *testing.T) {
		dbPath := filepath.Join(t.TempDir(), "test.db")
		config := Config{
			Key:      "test_reuse",
			Path:     dbPath,
			Lifetime: 30,
		}

		database1, db1, err := New(config)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer database1.Close()

		_, db2, err := New(config)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}

		if db1 != db2 {
			t.Error("expected same db instance for same key")
		}
	})

	t.Run("auto generate key from path", func(t *testing.T) {
		dbPath := filepath.Join(t.TempDir(), "mydb.db")
		database, db, err := New(Config{
			Path:     dbPath,
			Lifetime: 30,
		})
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer database.Close()

		if db == nil {
			t.Fatal("expected db instance, got nil")
		}
	})

	t.Run("invalid path", func(t *testing.T) {
		database, db, err := New(Config{
			Key:  "test_invalid",
			Path: "/invalid/path/db.db",
		})
		if err == nil {
			if database != nil {
				database.Close()
			}
			t.Fatal("expected error for invalid path")
		}
		if db != nil {
			t.Error("expected nil db on error")
		}
	})
}

func TestDatabaseClose(t *testing.T) {
	t.Run("close database successfully", func(t *testing.T) {
		database, _, _ := setupTestDB(t)
		database.Close()

		if database.db != nil {
			t.Error("expected db map to be nil after close")
		}
	})

	t.Run("close multiple databases", func(t *testing.T) {
		dbPath1 := filepath.Join(t.TempDir(), "test1.db")
		dbPath2 := filepath.Join(t.TempDir(), "test2.db")

		database, _, err := New(Config{Key: "db1", Path: dbPath1})
		if err != nil {
			t.Fatalf("failed to create db1: %v", err)
		}

		_, _, err = New(Config{Key: "db2", Path: dbPath2})
		if err != nil {
			t.Fatalf("failed to create db2: %v", err)
		}

		database.Close()

		if database.db != nil {
			t.Error("expected db map to be nil after close")
		}
	})
}

func TestBuilderCreate(t *testing.T) {
	t.Run("create table with basic columns", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{
					Name:         "id",
					Type:         "INTEGER",
					IsPrimary:    true,
					AutoIncrease: true,
				},
				Column{
					Name:       "name",
					Type:       "TEXT",
					IsNullable: false,
				},
			)

		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}

		var tableName string
		err = db.QueryRow("SELECT name FROM sqlite_master WHERE type='table' AND name='users'").Scan(&tableName)
		if err != nil {
			t.Fatalf("table not created: %v", err)
		}
		if tableName != "users" {
			t.Errorf("expected table name 'users', got %s", tableName)
		}
	})

	t.Run("create table with all column types", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("products").
			Create(
				Column{
					Name:         "id",
					Type:         "INTEGER",
					IsPrimary:    true,
					AutoIncrease: true,
				},
				Column{
					Name:       "name",
					Type:       "TEXT",
					IsNullable: false,
					IsUnique:   true,
				},
				Column{
					Name:    "price",
					Type:    "REAL",
					Default: 0.0,
				},
				Column{
					Name:       "description",
					Type:       "TEXT",
					IsNullable: true,
				},
			)

		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
	})

	t.Run("create table without table name", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Create(
				Column{Name: "id", Type: "INTEGER"},
			)

		if err == nil {
			t.Fatal("expected error for missing table name")
		}
	})

	t.Run("create table without columns", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("empty").
			Create()

		if err == nil {
			t.Fatal("expected error for empty columns")
		}
	})
}

func TestBuilderInsert(t *testing.T) {
	t.Run("insert single row", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT", IsNullable: false},
				Column{Name: "email", Type: "TEXT", IsNullable: false},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		err = NewBuilder(db).
			Table("users").
			Insert(map[string]any{
				"name":  "test",
				"email": "test@example.com",
			})

		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}

		var count int
		err = db.QueryRow("SELECT COUNT(*) FROM users").Scan(&count)
		if err != nil {
			t.Fatalf("failed to count rows: %v", err)
		}
		if count != 1 {
			t.Errorf("expected 1 row, got %d", count)
		}
	})

	t.Run("insert without table name", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Insert(map[string]any{"name": "test"})

		if err == nil {
			t.Fatal("expected error for missing table name")
		}
	})

	t.Run("insert with empty data", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Insert(map[string]any{})

		if err == nil {
			t.Fatal("expected error for empty data")
		}
	})
}

func TestBuilderInsertReturningID(t *testing.T) {
	t.Run("insert and return id", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT", IsNullable: false},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		id, err := NewBuilder(db).
			Table("users").
			InsertReturningID(map[string]any{
				"name": "test",
			})

		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if id != 1 {
			t.Errorf("expected id 1, got %d", id)
		}
	})

	t.Run("insert multiple rows and check incrementing id", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT", IsNullable: false},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		id1, _ := NewBuilder(db).Table("users").InsertReturningID(map[string]any{"name": "user1"})
		id2, _ := NewBuilder(db).Table("users").InsertReturningID(map[string]any{"name": "user2"})

		if id2 != id1+1 {
			t.Errorf("expected id2 to be %d, got %d", id1+1, id2)
		}
	})

	t.Run("insert returning id with error", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		_, err := NewBuilder(db).
			Table("nonexistent").
			InsertReturningID(map[string]any{"name": "test"})

		if err == nil {
			t.Fatal("expected error for nonexistent table")
		}
	})
}

func TestBuilderSelect(t *testing.T) {
	t.Run("select columns", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			Select("id", "name", "email")

		if len(builder.selectList) != 3 {
			t.Errorf("expected 3 columns, got %d", len(builder.selectList))
		}
		if builder.selectList[0] != "id" {
			t.Errorf("expected first column 'id', got %s", builder.selectList[0])
		}
	})

	t.Run("select all columns", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			Select("*")

		if len(builder.selectList) != 1 || builder.selectList[0] != "*" {
			t.Error("expected single '*' column")
		}
	})
}

func TestBuilderWhere(t *testing.T) {
	t.Run("single where condition", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			Where("id = ?", 1)

		if len(builder.whereList) != 1 {
			t.Errorf("expected 1 where condition, got %d", len(builder.whereList))
		}
		if builder.whereList[0].condition != "id = ?" {
			t.Errorf("expected condition 'id = ?', got %s", builder.whereList[0].condition)
		}
		if builder.whereList[0].operator != "AND" {
			t.Errorf("expected operator 'AND', got %s", builder.whereList[0].operator)
		}
		if len(builder.whereArgs) != 1 || builder.whereArgs[0] != 1 {
			t.Error("expected where args [1]")
		}
	})

	t.Run("multiple where conditions", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			Where("id = ?", 1).
			Where("status = ?", "active")

		if len(builder.whereList) != 2 {
			t.Errorf("expected 2 where conditions, got %d", len(builder.whereList))
		}
		if len(builder.whereArgs) != 2 {
			t.Errorf("expected 2 where args, got %d", len(builder.whereArgs))
		}
	})
}

func TestBuilderOrWhere(t *testing.T) {
	t.Run("or where condition", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			Where("id = ?", 1).
			OrWhere("id = ?", 2)

		if len(builder.whereList) != 2 {
			t.Errorf("expected 2 where conditions, got %d", len(builder.whereList))
		}
		if builder.whereList[1].operator != "OR" {
			t.Errorf("expected operator 'OR', got %s", builder.whereList[1].operator)
		}
	})
}

func TestBuilderJoin(t *testing.T) {
	t.Run("inner join", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			Join("orders", "users.id = orders.user_id")

		if len(builder.joinList) != 1 {
			t.Errorf("expected 1 join, got %d", len(builder.joinList))
		}
		if builder.joinList[0].mode != "INNER JOIN" {
			t.Errorf("expected 'INNER JOIN', got %s", builder.joinList[0].mode)
		}
		if builder.joinList[0].table != "orders" {
			t.Errorf("expected table 'orders', got %s", builder.joinList[0].table)
		}
		if builder.joinList[0].on != "users.id = orders.user_id" {
			t.Errorf("expected on clause, got %s", builder.joinList[0].on)
		}
	})

	t.Run("multiple joins", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			Join("orders", "users.id = orders.user_id").
			Join("products", "orders.product_id = products.id")

		if len(builder.joinList) != 2 {
			t.Errorf("expected 2 joins, got %d", len(builder.joinList))
		}
	})
}

func TestBuilderLeftJoin(t *testing.T) {
	t.Run("left join", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			LeftJoin("orders", "users.id = orders.user_id")

		if len(builder.joinList) != 1 {
			t.Errorf("expected 1 join, got %d", len(builder.joinList))
		}
		if builder.joinList[0].mode != "LEFT JOIN" {
			t.Errorf("expected 'LEFT JOIN', got %s", builder.joinList[0].mode)
		}
	})
}

func TestInsertConflict(t *testing.T) {
	t.Run("insert or ignore", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "email", Type: "TEXT", IsNullable: false, IsUnique: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		err = NewBuilder(db).
			Table("users").
			InsertConflict(Ignore, map[string]any{"email": "test@example.com"})
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}

		// Insert duplicate - should be ignored
		err = NewBuilder(db).
			Table("users").
			InsertConflict(Ignore, map[string]any{"email": "test@example.com"})
		if err != nil {
			t.Fatalf("expected no error for ignored conflict, got %v", err)
		}

		var count int
		_ = db.QueryRow("SELECT COUNT(*) FROM users").Scan(&count)
		if count != 1 {
			t.Errorf("expected 1 row, got %d", count)
		}
	})

	t.Run("insert or replace", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").InsertConflict(Replace, map[string]any{"id": 1, "name": "original"})
		_ = NewBuilder(db).Table("users").InsertConflict(Replace, map[string]any{"id": 1, "name": "replaced"})

		var name string
		_ = db.QueryRow("SELECT name FROM users WHERE id = 1").Scan(&name)
		if name != "replaced" {
			t.Errorf("expected 'replaced', got %s", name)
		}
	})

	t.Run("insert or abort", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").InsertConflict(Abort, map[string]any{"id": 1})
		err = NewBuilder(db).Table("users").InsertConflict(Abort, map[string]any{"id": 1})
		if err == nil {
			t.Fatal("expected error for abort on conflict")
		}
	})

	t.Run("insert or fail", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").InsertConflict(Fail, map[string]any{"id": 1})
		err = NewBuilder(db).Table("users").InsertConflict(Fail, map[string]any{"id": 1})
		if err == nil {
			t.Fatal("expected error for fail on conflict")
		}
	})

	t.Run("insert or rollback", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").InsertConflict(Rollback, map[string]any{"id": 1})
		err = NewBuilder(db).Table("users").InsertConflict(Rollback, map[string]any{"id": 1})
		if err == nil {
			t.Fatal("expected error for rollback on conflict")
		}
	})

	t.Run("insert conflict without table", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			InsertConflict(Ignore, map[string]any{"name": "test"})
		if err == nil {
			t.Fatal("expected error for missing table name")
		}
	})
}

func TestInsertConflictReturningID(t *testing.T) {
	t.Run("insert conflict returning id", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		id, err := NewBuilder(db).
			Table("users").
			InsertConflictReturningID(Ignore, map[string]any{"name": "test"})
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if id != 1 {
			t.Errorf("expected id 1, got %d", id)
		}
	})

	t.Run("insert conflict returning id with error", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		_, err := NewBuilder(db).
			Table("nonexistent").
			InsertConflictReturningID(Ignore, map[string]any{"name": "test"})
		if err == nil {
			t.Fatal("expected error for nonexistent table")
		}
	})
}

func TestInsertOnConflictDoUpdate(t *testing.T) {
	t.Run("on conflict do update", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		_, err := db.Exec(`CREATE TABLE users (
			id INTEGER PRIMARY KEY,
			email TEXT UNIQUE,
			name TEXT
		)`)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		// Insert initial row
		_ = NewBuilder(db).Table("users").Insert(
			map[string]any{"id": 1, "email": "test@example.com", "name": "original"},
		)

		// Insert with ON CONFLICT DO UPDATE
		err = NewBuilder(db).Table("users").Insert(
			map[string]any{"id": 1, "email": "test@example.com", "name": "should_be_ignored"},
			map[string]any{"name": "updated"},
		)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}

		var name string
		_ = db.QueryRow("SELECT name FROM users WHERE id = 1").Scan(&name)
		if name != "updated" {
			t.Errorf("expected 'updated', got %s", name)
		}
	})
}

func TestValidateColumn(t *testing.T) {
	t.Run("valid column names", func(t *testing.T) {
		validNames := []string{"id", "user_name", "Column1", "_private", "a", "A"}
		for _, name := range validNames {
			if err := validateColumn(name); err != nil {
				t.Errorf("expected %q to be valid, got error: %v", name, err)
			}
		}
	})

	t.Run("invalid column names", func(t *testing.T) {
		invalidNames := []string{"1invalid", "has space", "has-dash", "has.dot", "", "日本語"}
		for _, name := range invalidNames {
			if err := validateColumn(name); err == nil {
				t.Errorf("expected %q to be invalid", name)
			}
		}
	})
}

func TestFormatValue(t *testing.T) {
	tests := []struct {
		input    any
		expected string
	}{
		{"hello", "'hello'"},
		{123, "123"},
		{int64(456), "456"},
		{3.14, "3.14"},
		{true, "true"},
		{false, "false"},
		{[]byte("bytes"), "'[98 121 116 101 115]'"},
		{struct{ Name string }{"test"}, "'{test}'"},
	}

	for _, tt := range tests {
		t.Run(tt.expected, func(t *testing.T) {
			result := formatValue(tt.input)
			if result != tt.expected {
				t.Errorf("formatValue(%v) = %q, want %q", tt.input, result, tt.expected)
			}
		})
	}
}

func TestInsertWithInvalidColumn(t *testing.T) {
	t.Run("insert with invalid column name", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		err = NewBuilder(db).
			Table("users").
			Insert(map[string]any{"invalid-column": "test"})
		if err == nil {
			t.Fatal("expected error for invalid column name")
		}
	})

	t.Run("insert with invalid table name", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("invalid-table").
			Insert(map[string]any{"name": "test"})
		if err == nil {
			t.Fatal("expected error for invalid table name")
		}
	})
}

func TestCreateWithInvalidColumn(t *testing.T) {
	t.Run("create table with invalid column name", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "invalid-name", Type: "INTEGER"},
			)
		if err == nil {
			t.Fatal("expected error for invalid column name")
		}
	})
}

func TestCreateWithForeignKey(t *testing.T) {
	t.Run("create table with foreign key", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create users table: %v", err)
		}

		err = NewBuilder(db).
			Table("orders").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{
					Name: "user_id",
					Type: "INTEGER",
					ForeignKey: &Foreign{
						Table:  "users",
						Column: "id",
					},
				},
			)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
	})
}

func TestCreateWithDefaultString(t *testing.T) {
	t.Run("create table with string default", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "status", Type: "TEXT", Default: "active"},
			)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
	})
}

func TestInsertNoData(t *testing.T) {
	t.Run("insert with no data arguments", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Insert()
		if err == nil {
			t.Fatal("expected error for no data")
		}
	})
}

func TestInsertOnConflictWithInvalidUpdateColumn(t *testing.T) {
	t.Run("on conflict update with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		_, err := db.Exec(`CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT)`)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		err = NewBuilder(db).Table("users").Insert(
			map[string]any{"id": 1, "name": "test"},
			map[string]any{"invalid-column": "value"},
		)
		if err == nil {
			t.Fatal("expected error for invalid column in conflict update")
		}
	})
}

func TestBuilderOrderBy(t *testing.T) {
	t.Run("order by default ASC", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrderBy("name", Asc)

		if len(builder.orderBy) != 1 {
			t.Errorf("expected 1 order by clause, got %d", len(builder.orderBy))
		}
		if builder.orderBy[0] != `"name" ASC` {
			t.Errorf("expected '\"name\" ASC', got %s", builder.orderBy[0])
		}
	})

	t.Run("order by DESC", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrderBy("created_at", Desc)

		if builder.orderBy[0] != `"created_at" DESC` {
			t.Errorf("expected '\"created_at\" DESC', got %s", builder.orderBy[0])
		}
	})

	t.Run("multiple order by", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrderBy("name", Asc).
			OrderBy("id", Desc)

		if len(builder.orderBy) != 2 {
			t.Errorf("expected 2 order by clauses, got %d", len(builder.orderBy))
		}
	})
}

func TestBuilderLimit(t *testing.T) {
	t.Run("limit with single argument", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			Limit(10)

		if builder.limit == nil || *builder.limit != 10 {
			t.Error("expected limit 10")
		}
		if builder.offset != nil {
			t.Error("expected offset to be nil")
		}
	})

	t.Run("limit with two arguments (offset, limit)", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			Limit(5, 10)

		if builder.offset == nil || *builder.offset != 5 {
			t.Error("expected offset 5")
		}
		if builder.limit == nil || *builder.limit != 10 {
			t.Error("expected limit 10")
		}
	})

	t.Run("limit with no arguments", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			Limit()

		if builder.limit != nil {
			t.Error("expected limit to be nil")
		}
	})
}

func TestBuilderOffset(t *testing.T) {
	t.Run("offset", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			Offset(20)

		if builder.offset == nil || *builder.offset != 20 {
			t.Error("expected offset 20")
		}
	})
}

func TestBuilderGet(t *testing.T) {
	t.Run("get all rows", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT", IsNullable: false},
				Column{Name: "age", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice", "age": 30})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob", "age": 25})

		rows, err := NewBuilder(db).
			Table("users").
			Select("id", "name", "age").
			Get()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		var count int
		for rows.Next() {
			count++
		}
		if count != 2 {
			t.Errorf("expected 2 rows, got %d", count)
		}
	})

	t.Run("get with where clause", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob"})

		rows, err := NewBuilder(db).
			Table("users").
			Select("name").
			Where("name = ?", "Alice").
			Get()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		var name string
		if rows.Next() {
			_ = rows.Scan(&name)
		}
		if name != "Alice" {
			t.Errorf("expected 'Alice', got %s", name)
		}
	})

	t.Run("get with order by and limit", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Charlie"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob"})

		rows, err := NewBuilder(db).
			Table("users").
			Select("name").
			OrderBy("name", Asc).
			Limit(2).
			Get()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		var names []string
		for rows.Next() {
			var name string
			_ = rows.Scan(&name)
			names = append(names, name)
		}
		if len(names) != 2 {
			t.Errorf("expected 2 rows, got %d", len(names))
		}
		if names[0] != "Alice" {
			t.Errorf("expected first name 'Alice', got %s", names[0])
		}
	})

	t.Run("get with offset", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "A"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "B"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "C"})

		rows, err := NewBuilder(db).
			Table("users").
			Select("name").
			OrderBy("name", Asc).
			Limit(1).
			Offset(1).
			Get()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		var name string
		if rows.Next() {
			_ = rows.Scan(&name)
		}
		if name != "B" {
			t.Errorf("expected 'B', got %s", name)
		}
	})

	t.Run("get with join", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		_, _ = db.Exec(`CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT)`)
		_, _ = db.Exec(`CREATE TABLE orders (id INTEGER PRIMARY KEY, user_id INTEGER, amount REAL)`)
		_, _ = db.Exec(`INSERT INTO users (id, name) VALUES (1, 'Alice')`)
		_, _ = db.Exec(`INSERT INTO orders (id, user_id, amount) VALUES (1, 1, 100.50)`)

		rows, err := NewBuilder(db).
			Table("users").
			Select("*").
			Join("orders", "users.id = orders.user_id").
			Get()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		if !rows.Next() {
			t.Error("expected at least one row from join")
		}
	})

	t.Run("get with or where", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Charlie"})

		rows, err := NewBuilder(db).
			Table("users").
			Select("name").
			Where("name = ?", "Alice").
			OrWhere("name = ?", "Charlie").
			Get()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		var count int
		for rows.Next() {
			count++
		}
		if count != 2 {
			t.Errorf("expected 2 rows, got %d", count)
		}
	})

	t.Run("get without table name", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		_, err := NewBuilder(db).
			Select("name").
			Get()
		if err == nil {
			t.Fatal("expected error for missing table name")
		}
	})

	t.Run("get with invalid table name", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		_, err := NewBuilder(db).
			Table("invalid-table").
			Get()
		if err == nil {
			t.Fatal("expected error for invalid table name")
		}
	})

	t.Run("get with invalid column name", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_, err = NewBuilder(db).
			Table("users").
			Select("invalid-column").
			Get()
		if err == nil {
			t.Fatal("expected error for invalid column name")
		}
	})

	t.Run("get with select star only", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Test"})

		rows, err := NewBuilder(db).
			Table("users").
			Get()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		if !rows.Next() {
			t.Error("expected at least one row")
		}
	})
}

func TestBuilderFirst(t *testing.T) {
	t.Run("first returns single row", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob"})

		row, err := NewBuilder(db).
			Table("users").
			Select("name").
			OrderBy("name", Asc).
			First()
		if err != nil {
			t.Fatalf("First() failed: %v", err)
		}

		var name string
		err = row.Scan(&name)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if name != "Alice" {
			t.Errorf("expected 'Alice', got %s", name)
		}
	})

	t.Run("first with where clause", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob"})

		row, err := NewBuilder(db).
			Table("users").
			Select("name").
			Where("name = ?", "Bob").
			First()
		if err != nil {
			t.Fatalf("First() failed: %v", err)
		}

		var name string
		err = row.Scan(&name)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if name != "Bob" {
			t.Errorf("expected 'Bob', got %s", name)
		}
	})

	t.Run("first with no select columns", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Test"})

		row, err := NewBuilder(db).
			Table("users").
			First()
		if err != nil {
			t.Fatalf("First() failed: %v", err)
		}

		var id int
		var name string
		err = row.Scan(&id, &name)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if name != "Test" {
			t.Errorf("expected 'Test', got %s", name)
		}
	})
}

func TestBuilderCount(t *testing.T) {
	t.Run("count all rows", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Charlie"})

		count, err := NewBuilder(db).
			Table("users").
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 3 {
			t.Errorf("expected 3, got %d", count)
		}
	})

	t.Run("count with where clause", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "status", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"status": "active"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"status": "active"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"status": "inactive"})

		count, err := NewBuilder(db).
			Table("users").
			Where("status = ?", "active").
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("count without table name", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		_, err := NewBuilder(db).Count()
		if err == nil {
			t.Fatal("expected error for missing table name")
		}
	})

	t.Run("count empty table", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		count, err := NewBuilder(db).
			Table("users").
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 0 {
			t.Errorf("expected 0, got %d", count)
		}
	})
}

func TestBuilderTotal(t *testing.T) {
	t.Run("get with total", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Charlie"})

		rows, err := NewBuilder(db).
			Table("users").
			Select("id", "name").
			Total().
			Limit(2).
			Get()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		var count int
		for rows.Next() {
			var total, id int
			var name string
			err := rows.Scan(&total, &id, &name)
			if err != nil {
				t.Fatalf("scan error: %v", err)
			}
			if total != 3 {
				t.Errorf("expected total 3, got %d", total)
			}
			count++
		}
		if count != 2 {
			t.Errorf("expected 2 rows returned, got %d", count)
		}
	})

	t.Run("total returns builder", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			Total()

		if !builder.withTotal {
			t.Error("expected withTotal to be true")
		}
	})
}

func TestWhereHelpers(t *testing.T) {
	t.Run("WhereEq", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob"})

		rows, err := NewBuilder(db).
			Table("users").
			Select("name").
			WhereEq("name", "Alice").
			Get()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		var name string
		if rows.Next() {
			_ = rows.Scan(&name)
		}
		if name != "Alice" {
			t.Errorf("expected 'Alice', got %s", name)
		}
	})

	t.Run("WhereEq with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereEq("invalid-column", "value")

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("WhereNotEq", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob"})

		rows, err := NewBuilder(db).
			Table("users").
			Select("name").
			WhereNotEq("name", "Alice").
			Get()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		var name string
		if rows.Next() {
			_ = rows.Scan(&name)
		}
		if name != "Bob" {
			t.Errorf("expected 'Bob', got %s", name)
		}
	})

	t.Run("WhereNotEq with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereNotEq("invalid-column", "value")

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("WhereGt", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "age", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 20})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 30})

		count, err := NewBuilder(db).
			Table("users").
			WhereGt("age", 25).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 1 {
			t.Errorf("expected 1, got %d", count)
		}
	})

	t.Run("WhereGt with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereGt("invalid-column", 10)

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("WhereLt", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "age", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 20})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 30})

		count, err := NewBuilder(db).
			Table("users").
			WhereLt("age", 25).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 1 {
			t.Errorf("expected 1, got %d", count)
		}
	})

	t.Run("WhereLt with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereLt("invalid-column", 10)

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("WhereGe", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "age", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 20})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 25})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 30})

		count, err := NewBuilder(db).
			Table("users").
			WhereGe("age", 25).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("WhereGe with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereGe("invalid-column", 10)

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("WhereLe", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "age", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 20})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 25})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 30})

		count, err := NewBuilder(db).
			Table("users").
			WhereLe("age", 25).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("WhereLe with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereLe("invalid-column", 10)

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("WhereIn", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Charlie"})

		count, err := NewBuilder(db).
			Table("users").
			WhereIn("name", []any{"Alice", "Charlie"}).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("WhereIn with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereIn("invalid-column", []any{"a", "b"})

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("WhereIn with empty values", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereIn("name", []any{})

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for empty values")
		}
	})

	t.Run("WhereNotIn", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Charlie"})

		count, err := NewBuilder(db).
			Table("users").
			WhereNotIn("name", []any{"Alice", "Charlie"}).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 1 {
			t.Errorf("expected 1, got %d", count)
		}
	})

	t.Run("WhereNotIn with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereNotIn("invalid-column", []any{"a", "b"})

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("WhereNotIn with empty values", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereNotIn("name", []any{})

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for empty values")
		}
	})

	t.Run("WhereNull", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "email", Type: "TEXT", IsNullable: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_, _ = db.Exec("INSERT INTO users (email) VALUES (NULL)")
		_, _ = db.Exec("INSERT INTO users (email) VALUES ('test@example.com')")

		count, err := NewBuilder(db).
			Table("users").
			WhereNull("email").
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 1 {
			t.Errorf("expected 1, got %d", count)
		}
	})

	t.Run("WhereNull with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereNull("invalid-column")

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("WhereNotNull", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "email", Type: "TEXT", IsNullable: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_, _ = db.Exec("INSERT INTO users (email) VALUES (NULL)")
		_, _ = db.Exec("INSERT INTO users (email) VALUES ('test@example.com')")

		count, err := NewBuilder(db).
			Table("users").
			WhereNotNull("email").
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 1 {
			t.Errorf("expected 1, got %d", count)
		}
	})

	t.Run("WhereNotNull with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereNotNull("invalid-column")

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("WhereBetween", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "age", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 15})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 25})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 35})

		count, err := NewBuilder(db).
			Table("users").
			WhereBetween("age", 20, 30).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 1 {
			t.Errorf("expected 1, got %d", count)
		}
	})

	t.Run("WhereBetween with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			WhereBetween("invalid-column", 10, 20)

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})
}

func TestOrWhereHelpers(t *testing.T) {
	t.Run("OrWhereEq", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Bob"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"name": "Charlie"})

		count, err := NewBuilder(db).
			Table("users").
			WhereEq("name", "Alice").
			OrWhereEq("name", "Bob").
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("OrWhereEq with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereEq("invalid-column", "value")

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("OrWhereNotEq", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "status", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"status": "active"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"status": "pending"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"status": "inactive"})

		count, err := NewBuilder(db).
			Table("users").
			WhereEq("status", "active").
			OrWhereNotEq("status", "inactive").
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("OrWhereNotEq with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereNotEq("invalid-column", "value")

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("OrWhereGt", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "age", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 15})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 25})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 35})

		count, err := NewBuilder(db).
			Table("users").
			WhereLt("age", 20).
			OrWhereGt("age", 30).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("OrWhereGt with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereGt("invalid-column", 10)

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("OrWhereLt", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "age", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 15})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 25})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 35})

		count, err := NewBuilder(db).
			Table("users").
			WhereGt("age", 30).
			OrWhereLt("age", 20).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("OrWhereLt with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereLt("invalid-column", 10)

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("OrWhereGe", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "age", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 15})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 25})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 35})

		count, err := NewBuilder(db).
			Table("users").
			WhereLt("age", 20).
			OrWhereGe("age", 35).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("OrWhereGe with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereGe("invalid-column", 10)

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("OrWhereLe", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "age", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 15})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 25})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 35})

		count, err := NewBuilder(db).
			Table("users").
			WhereGt("age", 30).
			OrWhereLe("age", 15).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("OrWhereLe with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereLe("invalid-column", 10)

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("OrWhereIn", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "status", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"status": "active"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"status": "pending"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"status": "inactive"})

		count, err := NewBuilder(db).
			Table("users").
			WhereEq("status", "active").
			OrWhereIn("status", []any{"pending", "inactive"}).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 3 {
			t.Errorf("expected 3, got %d", count)
		}
	})

	t.Run("OrWhereIn with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereIn("invalid-column", []any{"a", "b"})

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("OrWhereIn with empty values", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereIn("status", []any{})

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for empty values")
		}
	})

	t.Run("OrWhereNotIn", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "status", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"status": "active"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"status": "pending"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"status": "inactive"})

		count, err := NewBuilder(db).
			Table("users").
			WhereEq("status", "active").
			OrWhereNotIn("status", []any{"active", "pending"}).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("OrWhereNotIn with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereNotIn("invalid-column", []any{"a", "b"})

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("OrWhereNotIn with empty values", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereNotIn("status", []any{})

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for empty values")
		}
	})

	t.Run("OrWhereNull", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "email", Type: "TEXT", IsNullable: true},
				Column{Name: "phone", Type: "TEXT", IsNullable: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_, _ = db.Exec("INSERT INTO users (email, phone) VALUES ('a@a.com', NULL)")
		_, _ = db.Exec("INSERT INTO users (email, phone) VALUES (NULL, '123')")
		_, _ = db.Exec("INSERT INTO users (email, phone) VALUES ('b@b.com', '456')")

		count, err := NewBuilder(db).
			Table("users").
			WhereNull("email").
			OrWhereNull("phone").
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("OrWhereNull with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereNull("invalid-column")

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("OrWhereNotNull", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "email", Type: "TEXT", IsNullable: true},
				Column{Name: "phone", Type: "TEXT", IsNullable: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_, _ = db.Exec("INSERT INTO users (email, phone) VALUES ('a@a.com', NULL)")
		_, _ = db.Exec("INSERT INTO users (email, phone) VALUES (NULL, '123')")
		_, _ = db.Exec("INSERT INTO users (email, phone) VALUES (NULL, NULL)")

		count, err := NewBuilder(db).
			Table("users").
			WhereNotNull("email").
			OrWhereNotNull("phone").
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("OrWhereNotNull with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereNotNull("invalid-column")

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})

	t.Run("OrWhereBetween", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true, AutoIncrease: true},
				Column{Name: "age", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 10})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 25})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 40})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"age": 55})

		count, err := NewBuilder(db).
			Table("users").
			WhereBetween("age", 20, 30).
			OrWhereBetween("age", 50, 60).
			Count()
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 2 {
			t.Errorf("expected 2, got %d", count)
		}
	})

	t.Run("OrWhereBetween with invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		builder := NewBuilder(db).
			Table("users").
			OrWhereBetween("invalid-column", 10, 20)

		if len(builder.whereList) != 0 {
			t.Error("expected no where clause for invalid column")
		}
	})
}

func TestDatabaseDB(t *testing.T) {
	t.Run("get builder from existing db", func(t *testing.T) {
		database, _, _ := setupTestDB(t)
		defer database.Close()

		builder, err := database.DB("test_" + t.Name())
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if builder == nil {
			t.Fatal("expected builder, got nil")
		}
	})

	t.Run("get builder from non-existent db", func(t *testing.T) {
		database, _, _ := setupTestDB(t)
		defer database.Close()

		_, err := database.DB("non_existent_key")
		if err == nil {
			t.Fatal("expected error for non-existent db")
		}
	})
}

func TestDatabaseQuery(t *testing.T) {
	t.Run("query existing db", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "name": "Alice"})

		rows, err := database.Query("test_"+t.Name(), "SELECT * FROM users")
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		if !rows.Next() {
			t.Fatal("expected at least one row")
		}
	})

	t.Run("query non-existent db", func(t *testing.T) {
		database, _, _ := setupTestDB(t)
		defer database.Close()

		_, err := database.Query("non_existent_key", "SELECT 1")
		if err == nil {
			t.Fatal("expected error for non-existent db")
		}
	})
}

func TestDatabaseQueryContext(t *testing.T) {
	t.Run("query with context", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1})

		ctx := t.Context()
		rows, err := database.QueryContext(ctx, "test_"+t.Name(), "SELECT * FROM users")
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		if !rows.Next() {
			t.Fatal("expected at least one row")
		}
	})

	t.Run("query context non-existent db", func(t *testing.T) {
		database, _, _ := setupTestDB(t)
		defer database.Close()

		ctx := t.Context()
		_, err := database.QueryContext(ctx, "non_existent_key", "SELECT 1")
		if err == nil {
			t.Fatal("expected error for non-existent db")
		}
	})
}

func TestDatabaseExec(t *testing.T) {
	t.Run("exec on existing db", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		result, err := database.Exec("test_"+t.Name(), "INSERT INTO users (id) VALUES (?)", 1)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}

		affected, _ := result.RowsAffected()
		if affected != 1 {
			t.Errorf("expected 1 row affected, got %d", affected)
		}
	})

	t.Run("exec on non-existent db", func(t *testing.T) {
		database, _, _ := setupTestDB(t)
		defer database.Close()

		_, err := database.Exec("non_existent_key", "SELECT 1")
		if err == nil {
			t.Fatal("expected error for non-existent db")
		}
	})
}

func TestDatabaseExecContext(t *testing.T) {
	t.Run("exec with context", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		ctx := t.Context()
		result, err := database.ExecContext(ctx, "test_"+t.Name(), "INSERT INTO users (id) VALUES (?)", 1)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}

		affected, _ := result.RowsAffected()
		if affected != 1 {
			t.Errorf("expected 1 row affected, got %d", affected)
		}
	})

	t.Run("exec context non-existent db", func(t *testing.T) {
		database, _, _ := setupTestDB(t)
		defer database.Close()

		ctx := t.Context()
		_, err := database.ExecContext(ctx, "non_existent_key", "SELECT 1")
		if err == nil {
			t.Fatal("expected error for non-existent db")
		}
	})
}

func TestGetContext(t *testing.T) {
	t.Run("get with context", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 2, "name": "Bob"})

		ctx := t.Context()
		rows, err := NewBuilder(db).
			Table("users").
			Select("name").
			GetContext(ctx)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		defer rows.Close()

		count := 0
		for rows.Next() {
			count++
		}
		if count != 2 {
			t.Errorf("expected 2 rows, got %d", count)
		}
	})
}

func TestFirstContext(t *testing.T) {
	t.Run("first with context", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "name": "Alice"})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 2, "name": "Bob"})

		ctx := t.Context()
		row, err := NewBuilder(db).
			Table("users").
			Select("name").
			OrderBy("name", Asc).
			FirstContext(ctx)
		if err != nil {
			t.Fatalf("FirstContext() failed: %v", err)
		}

		var name string
		err = row.Scan(&name)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if name != "Alice" {
			t.Errorf("expected 'Alice', got %s", name)
		}
	})
}

func TestCountContext(t *testing.T) {
	t.Run("count with context", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 2})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 3})

		ctx := t.Context()
		count, err := NewBuilder(db).
			Table("users").
			CountContext(ctx)
		if err != nil {
			t.Fatalf("expected no error, got %v", err)
		}
		if count != 3 {
			t.Errorf("expected 3, got %d", count)
		}
	})
}

func TestInsertContext(t *testing.T) {
	t.Run("insert with context", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		ctx := t.Context()
		err = NewBuilder(db).
			Table("users").
			InsertContext(ctx, map[string]any{"id": 1, "name": "Alice"})
		if err != nil {
			t.Fatalf("InsertContext() failed: %v", err)
		}

		count, _ := NewBuilder(db).Table("users").Count()
		if count != 1 {
			t.Errorf("expected 1 row, got %d", count)
		}
	})

	t.Run("insert context no table", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		ctx := t.Context()
		err := NewBuilder(db).
			InsertContext(ctx, map[string]any{"id": 1})
		if err == nil {
			t.Fatal("expected error for missing table")
		}
	})
}

func TestInsertContextReturningID(t *testing.T) {
	t.Run("insert context returning id", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		ctx := t.Context()
		id, err := NewBuilder(db).
			Table("users").
			InsertContextReturningID(ctx, map[string]any{"id": 1, "name": "Alice"})
		if err != nil {
			t.Fatalf("InsertContextReturningID() failed: %v", err)
		}
		if id != 1 {
			t.Errorf("expected id 1, got %d", id)
		}
	})

	t.Run("insert context returning id no table", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		ctx := t.Context()
		_, err := NewBuilder(db).
			InsertContextReturningID(ctx, map[string]any{"id": 1})
		if err == nil {
			t.Fatal("expected error for missing table")
		}
	})
}

func TestInsertContexConflict(t *testing.T) {
	t.Run("insert context conflict ignore", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		ctx := t.Context()
		err = NewBuilder(db).
			Table("users").
			InsertContexConflict(ctx, Ignore, map[string]any{"id": 1, "name": "Alice"})
		if err != nil {
			t.Fatalf("InsertContexConflict() failed: %v", err)
		}

		err = NewBuilder(db).
			Table("users").
			InsertContexConflict(ctx, Ignore, map[string]any{"id": 1, "name": "Bob"})
		if err != nil {
			t.Fatalf("InsertContexConflict() with duplicate should not fail with Ignore: %v", err)
		}

		count, _ := NewBuilder(db).Table("users").Count()
		if count != 1 {
			t.Errorf("expected 1 row after conflict ignore, got %d", count)
		}
	})

	t.Run("insert context conflict no table", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		ctx := t.Context()
		err := NewBuilder(db).
			InsertContexConflict(ctx, Ignore, map[string]any{"id": 1})
		if err == nil {
			t.Fatal("expected error for missing table")
		}
	})
}

func TestInsertContextConflictReturningID(t *testing.T) {
	t.Run("insert context conflict returning id", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		ctx := t.Context()
		id, err := NewBuilder(db).
			Table("users").
			InsertContextConflictReturningID(ctx, Replace, map[string]any{"id": 1, "name": "Alice"})
		if err != nil {
			t.Fatalf("InsertContextConflictReturningID() failed: %v", err)
		}
		if id != 1 {
			t.Errorf("expected id 1, got %d", id)
		}
	})

	t.Run("insert context conflict returning id no table", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		ctx := t.Context()
		_, err := NewBuilder(db).
			InsertContextConflictReturningID(ctx, Replace, map[string]any{"id": 1})
		if err == nil {
			t.Fatal("expected error for missing table")
		}
	})
}

func TestUpdate(t *testing.T) {
	t.Run("update single row", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "name", Type: "TEXT"},
				Column{Name: "age", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "name": "Alice", "age": 25})
		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 2, "name": "Bob", "age": 30})

		result, err := NewBuilder(db).
			Table("users").
			WhereEq("id", 1).
			Update(map[string]any{"name": "Alicia", "age": 26})
		if err != nil {
			t.Fatalf("Update() failed: %v", err)
		}

		affected, _ := result.RowsAffected()
		if affected != 1 {
			t.Errorf("expected 1 affected row, got %d", affected)
		}

		rows, _ := NewBuilder(db).Table("users").Select("name", "age").WhereEq("id", 1).Get()
		defer rows.Close()
		rows.Next()
		var name string
		var age int
		rows.Scan(&name, &age)
		if name != "Alicia" || age != 26 {
			t.Errorf("expected (Alicia, 26), got (%s, %d)", name, age)
		}
	})

	t.Run("update no table", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		_, err := NewBuilder(db).
			Update(map[string]any{"name": "Test"})
		if err == nil {
			t.Fatal("expected error for missing table")
		}
	})

	t.Run("update no data", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_, err = NewBuilder(db).
			Table("users").
			Update(map[string]any{})
		if err == nil {
			t.Fatal("expected error for no data")
		}
	})

	t.Run("update invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_, err = NewBuilder(db).
			Table("users").
			Update(map[string]any{"invalid;column": "value"})
		if err == nil {
			t.Fatal("expected error for invalid column name")
		}
	})
}

func TestUpdateContext(t *testing.T) {
	t.Run("update with context", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "name", Type: "TEXT"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "name": "Alice"})

		ctx := t.Context()
		result, err := NewBuilder(db).
			Table("users").
			WhereEq("id", 1).
			UpdateContext(ctx, map[string]any{"name": "Alicia"})
		if err != nil {
			t.Fatalf("UpdateContext() failed: %v", err)
		}

		affected, _ := result.RowsAffected()
		if affected != 1 {
			t.Errorf("expected 1 affected row, got %d", affected)
		}
	})

	t.Run("update context no table", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		ctx := t.Context()
		_, err := NewBuilder(db).
			UpdateContext(ctx, map[string]any{"name": "Test"})
		if err == nil {
			t.Fatal("expected error for missing table")
		}
	})
}

func TestIncrease(t *testing.T) {
	t.Run("increase default value", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "count", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "count": 10})

		_, err = NewBuilder(db).
			Table("users").
			WhereEq("id", 1).
			Increase("count").
			Update(map[string]any{})
		if err != nil {
			t.Fatalf("Increase() failed: %v", err)
		}

		rows, _ := NewBuilder(db).Table("users").Select("count").WhereEq("id", 1).Get()
		defer rows.Close()
		rows.Next()
		var count int
		rows.Scan(&count)
		if count != 11 {
			t.Errorf("expected 11, got %d", count)
		}
	})

	t.Run("increase custom value", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "count", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "count": 10})

		_, err = NewBuilder(db).
			Table("users").
			WhereEq("id", 1).
			Increase("count", 5).
			Update(map[string]any{})
		if err != nil {
			t.Fatalf("Increase() failed: %v", err)
		}

		rows, _ := NewBuilder(db).Table("users").Select("count").WhereEq("id", 1).Get()
		defer rows.Close()
		rows.Next()
		var count int
		rows.Scan(&count)
		if count != 15 {
			t.Errorf("expected 15, got %d", count)
		}
	})

	t.Run("increase invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "count", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "count": 10})

		builder := NewBuilder(db).
			Table("users").
			WhereEq("id", 1).
			Increase("invalid;column")
		if builder == nil {
			t.Fatal("expected builder to be returned even with invalid column")
		}
	})
}

func TestDecrease(t *testing.T) {
	t.Run("decrease default value", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "count", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "count": 10})

		_, err = NewBuilder(db).
			Table("users").
			WhereEq("id", 1).
			Decrease("count").
			Update(map[string]any{})
		if err != nil {
			t.Fatalf("Decrease() failed: %v", err)
		}

		rows, _ := NewBuilder(db).Table("users").Select("count").WhereEq("id", 1).Get()
		defer rows.Close()
		rows.Next()
		var count int
		rows.Scan(&count)
		if count != 9 {
			t.Errorf("expected 9, got %d", count)
		}
	})

	t.Run("decrease custom value", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "count", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "count": 10})

		_, err = NewBuilder(db).
			Table("users").
			WhereEq("id", 1).
			Decrease("count", 3).
			Update(map[string]any{})
		if err != nil {
			t.Fatalf("Decrease() failed: %v", err)
		}

		rows, _ := NewBuilder(db).Table("users").Select("count").WhereEq("id", 1).Get()
		defer rows.Close()
		rows.Next()
		var count int
		rows.Scan(&count)
		if count != 7 {
			t.Errorf("expected 7, got %d", count)
		}
	})

	t.Run("decrease invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "count", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		builder := NewBuilder(db).
			Table("users").
			Decrease("invalid;column")
		if builder == nil {
			t.Fatal("expected builder to be returned even with invalid column")
		}
	})
}

func TestToggle(t *testing.T) {
	t.Run("toggle boolean value", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "active", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "active": 1})

		_, err = NewBuilder(db).
			Table("users").
			WhereEq("id", 1).
			Toggle("active").
			Update(map[string]any{})
		if err != nil {
			t.Fatalf("Toggle() failed: %v", err)
		}

		rows, _ := NewBuilder(db).Table("users").Select("active").WhereEq("id", 1).Get()
		defer rows.Close()
		rows.Next()
		var active int
		rows.Scan(&active)
		if active != 0 {
			t.Errorf("expected 0 after toggle, got %d", active)
		}
	})

	t.Run("toggle false to true", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "active", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "active": 0})

		_, err = NewBuilder(db).
			Table("users").
			WhereEq("id", 1).
			Toggle("active").
			Update(map[string]any{})
		if err != nil {
			t.Fatalf("Toggle() failed: %v", err)
		}

		rows, _ := NewBuilder(db).Table("users").Select("active").WhereEq("id", 1).Get()
		defer rows.Close()
		rows.Next()
		var active int
		rows.Scan(&active)
		if active != 1 {
			t.Errorf("expected 1 after toggle, got %d", active)
		}
	})

	t.Run("toggle invalid column", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		builder := NewBuilder(db).
			Table("users").
			Toggle("invalid;column")
		if builder == nil {
			t.Fatal("expected builder to be returned even with invalid column")
		}
	})
}

func TestUpdateWithIncreaseAndData(t *testing.T) {
	t.Run("update with both increase and data", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		err := NewBuilder(db).
			Table("users").
			Create(
				Column{Name: "id", Type: "INTEGER", IsPrimary: true},
				Column{Name: "name", Type: "TEXT"},
				Column{Name: "count", Type: "INTEGER"},
			)
		if err != nil {
			t.Fatalf("failed to create table: %v", err)
		}

		_ = NewBuilder(db).Table("users").Insert(map[string]any{"id": 1, "name": "Alice", "count": 10})

		_, err = NewBuilder(db).
			Table("users").
			WhereEq("id", 1).
			Increase("count", 5).
			Update(map[string]any{"name": "Alicia"})
		if err != nil {
			t.Fatalf("Update() with Increase failed: %v", err)
		}

		rows, _ := NewBuilder(db).Table("users").Select("name", "count").WhereEq("id", 1).Get()
		defer rows.Close()
		rows.Next()
		var name string
		var count int
		rows.Scan(&name, &count)
		if name != "Alicia" || count != 15 {
			t.Errorf("expected (Alicia, 15), got (%s, %d)", name, count)
		}
	})
}

func TestUpdateInvalidTable(t *testing.T) {
	t.Run("update with invalid table name", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		_, err := NewBuilder(db).
			Table("invalid;table").
			Update(map[string]any{"name": "Test"})
		if err == nil {
			t.Fatal("expected error for invalid table name")
		}
	})
}

func TestGetContextError(t *testing.T) {
	t.Run("get context no table", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		ctx := t.Context()
		_, err := NewBuilder(db).
			Select("id").
			GetContext(ctx)
		if err == nil {
			t.Fatal("expected error for missing table")
		}
	})
}

func TestFirstError(t *testing.T) {
	t.Run("first no table", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		_, err := NewBuilder(db).
			Select("id").
			First()
		if err == nil {
			t.Fatal("expected error for missing table")
		}
	})
}

func TestFirstContextError(t *testing.T) {
	t.Run("first context no table", func(t *testing.T) {
		database, db, _ := setupTestDB(t)
		defer database.Close()

		ctx := t.Context()
		_, err := NewBuilder(db).
			Select("id").
			FirstContext(ctx)
		if err == nil {
			t.Fatal("expected error for missing table")
		}
	})
}
